spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: c##java
        password: 12345
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.highlight_sql: true
    application:
        name: shop
    elasticsearch:
        uris: http://localhost:9200

server:
  servlet:
    encoding:
      enabled: true

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
        org.elasticsearch.client: trace

